apiVersion: v1
kind: Pod
metadata:
  name: dali
spec:  # specification of the pod’s contents
  restartPolicy: Never
  containers:
  - name:  dali
    image: "hpccsystems/platform"
    volumeMounts:
    - mountPath: "/var/lib/HPCCSystems"
      name: dali-data
  volumes:
  - name: dali-data
    persistentVolumeClaim:
      claimName: ebs-dali
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dali
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 40Gi
