apiVersion: apps/v1
kind: Deployment
metadata:
  name: support
  labels:
    app: support
spec:  # specification of the pod’s contents
  replicas: 1
  selector:
    matchLabels:
      app: support
      cluster: support
  template:
    metadata:
      labels:
        app: support
        cluster: support
    spec:
      containers:
      - name: support
        image: "hpccsystems/platform"
        volumeMounts:
        - mountPath: "/var/lib/HPCCSystems"
          name: support-data
      volumes:
      - name: support-data
        persistentVolumeClaim:
          claimName: ebs-support
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-support
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: gp2
  resources:
    requests:
      storage: 40Gi
