apiVersion: v1
kind: ReplicationController
metadata:
  name: roxie-controller
spec:
  replicas: 1
  selector:
    app: roxie
  template:
    metadata:
      labels:
        app: roxie
    spec:
      containers:
        - name: roxie
          image: "hpccsystems/platform-ce:6.0.2-1trusty"
          volumeMounts:
            - mountPath: "/hpcc-share"
              name: nfs
            - mountPath: "/disk1"
              name: disk1
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs
        - name: disk1
          awsElasticBlockStore:
            volumeID: vol-233c99fe
            fsType: ext4
