apiVersion: v1
kind: PersistentVolume
metadata:
  name: support-data
spec:
  capacity:
    storage: 160Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "<VOLUME-ID>"
