apiVersion: v1
kind: Service
metadata:
  name: svc-thor-thor1
  # namespace: default
  labels:
    app: thor-thor1
spec:
  selector:
    app: svc-thor-thor1
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thor-thor1
spec:  # specification of the pod’s contents
  serviceName: "svc-thor-thor1"
  replicas: 10
  podManagementPolicy: "Parallel"  # the default is "OrderedReady"
  selector:
    matchLabels:
      app: svc-thor-thor1
  template:
    metadata:
      labels:
        app: svc-thor-thor1
    spec:
      containers:
      - name:  thor-thor1
        image: "hpccsystems/platform"
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
        volumeMounts:
        - mountPath: "/var/lib/HPCCSystems"
          name: ebs
  volumeClaimTemplates:
  - metadata:
      name: ebs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp2
      resources:
        requests:
          storage: 60Gi
