apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: esp-e1
  #namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: esp-e1
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
  #targetCPUUtilizationPercentage: 5 # for easy to test
