apiVersion: apps/v1
kind: Deployment
metadata:
  name: thor-{{ .Values.Thor.Cluster1.Name }}
  namespace: {{ .Values.NameSpace.Name }}
  labels:
    app: thor-{{ .Values.Thor.Cluster1.Name }}
spec:  # specification of the pod’s contents
  replicas: {{ .Values.Thor.Cluster1.Replicas }}
  selector:
    matchLabels:
      app: thor-{{ .Values.Thor.Cluster1.Name }}
      cluster: {{ .Values.Thor.Cluster1.Name }}
  template:
    metadata:
      labels:
        app: thor-{{ .Values.Thor.Cluster1.Name }}
        cluster: {{ .Values.Thor.Cluster1.Name }}
    spec:
      containers:
      - name:  thor-{{ .Values.Thor.Cluster1.Name }}
        image: {{ .Values.Hpccsystems.Platform.Image }}
        {{- if .Values.AWS.EFS.Enabled }}
        volumeMounts:
        - mountPath: "/var/lib/HPCCSystems/hpcc-data"
          name: thor1-data
        - mountPath: "/var/lib/HPCCSystems/hpcc-mirror"
          name: thor1-mirror
        - mountPath: "/var/lib/HPCCSystems/queries"
          name: thor1-queries
        {{- end }}
      {{- if .Values.AWS.EFS.Enabled }}
      volumes:
      - name:  thor1-data
        persistentVolumeClaim:
          claimName: {{ .Values.global.EFS.ClaimName.Data }}
      - name: thor1-mirror
        persistentVolumeClaim:
          claimName: {{ .Values.global.EFS.ClaimName.Mirror }}
      - name: thor1-queries
        persistentVolumeClaim:
          claimName: {{ .Values.global.EFS.ClaimName.Queries }}
      {{- end }}
