# This should be created automatically in EKS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
  provisioner: kubernetes.io/aws-ebs
  annotation:
    storageclass.kubernetes.io/is-default-class: true
  parameters:
    type: gp2
  reclaimPolicy: Retain
  #mountOptions:
  #  - debug
  volumeBindingMode: Immediate
