apiVersion: v1
kind: Service
metadata:
  name: ew-esp1
#  namespace: default
spec:
  selector:
    app: esp-esp1
  ports:
  - protocol: TCP
    port: 18010
    targetPort: 18010
    name: eclwatch-https
  - protocol: TCP
    port: 18002
    targetPort: 18002
    name: wsecl-https
  - protocol: TCP
    port: 18510
    targetPort: 18510
    name: wssql-https
  - protocol: TCP
    port: 18015
    targetPort: 18015
    name: confmgr-https
  type:
    LoadBalancer
    #NodePort   #local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esp-esp1
  labels:
    app: esp-esp1
spec:  # specification of the pod’s contents
  replicas: 1
  selector:
     matchLabels:
       app: esp-esp1
       cluster: esp1
  template:
    metadata:
      labels:
        cluster: esp1
        app: esp-esp1
    spec:
      containers:
      - name: esp-esp1
        image: "hpccsystems/platform"
        ports:
        - name: eclwatch-https
          containerPort: 18010
        - name: wsecl-https
          containerPort: 18010
        - name: wsssql-https
          containerPort: 18510
        - name: confmgr-https
          containerPort: 18015
