apiVersion: v1
kind: ReplicationController
metadata:
  name: thor-thor1
spec:  # specification of the pod’s contents
  replicas: 1
  selector:
     cluster: thor1
  template:
    metadata:
      labels:
        cluster: thor1
    spec:
      containers:
        - name:  thor-thor1
          image: "hpccsystems/platform"
