apiVersion: v1
kind: Service
metadata:
  name: roxie-roxie1
  # namespace: default
  labels:
    app: roxie-roxie1
    service: roxie-roxie1
spec:
  selector:
    app: roxie-roxie1
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roxie-roxie1
  labels:
    app: roxie-roxie1
spec:  # specification of the pod’s contents
  replicas: 1
  selector:
    matchLabels:
      app: roxie-roxie1
      cluster: roxie1
  template:
    metadata:
      labels:
        app: roxie-roxie1
        cluster: roxie1
    spec:
      containers:
        - name:  roxie-roxie1
          image: "hpccsystems/platform"
