#!/bin/bash
WORK_DIR=$(dirname $0)
. ${WORK_DIR}/../../bin/common

${KUBECTL} create -f admin.yaml
${KUBECTL} create -f support.yaml
#${KUBECTL} create -f esp-e1.yaml
istioctl kube-inject -f esp-e1.yaml | ${KUBECTL} apply -f -
${KUBECTL} create -f roxie-r1.yaml
#${KUBECTL} create -f thormaster-t1.yaml
#${KUBECTL} create -f thor-t1.yaml
