apiVersion: v1
kind: ReplicationController
metadata:
  name: esp-e1
spec:  # specification of the pod’s contents
  replicas: 1
  selector:
     cluster: e1
  template:
    metadata:
      labels:
        cluster: e1
    spec:
      containers:
        - name: esp-e1
          image: "hpccsystems/hpcc:7.2.20-1"
          ports:
            - name: eclwatch
              containerPort: 8010
            - name: wsecl
              containerPort: 8010
            - name: roxie
              containerPort: 9876
