apiVersion: v1
kind: ReplicationController
metadata:
  name: roxie-roxie1
spec:  # specification of the pod’s contents
  replicas: 1
  selector:
     cluster: roxie1
  template:
    metadata:
      labels:
        cluster: roxie1
    spec:
      containers:
        - name:  roxie-roxie1
          image: "hpccsystems/hpcc:7.2.20-1"
