apiVersion: v1
kind: ReplicationController
metadata:
  name: support
spec:  # specification of the pod’s contents
  replicas: 1
  selector:
     cluster: support
  template:
    metadata:
      labels:
        cluster: support
    spec:
      containers:
        - name: support
          image: "hpccsystems/hpcc:7.2.20-1"
