apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.Admin.ConfigMap.Name }}
  labels:
    app: {{ include "hpccsystems-name" . }}
    chart: {{ include "hpccsystems-chart" . }}
    release: {{ .Release.Name }}
data:
  topology.properties: |
    thor1.name=thor1
    thor1.eclagent=myeclagent
    thor1.eclccserver=myeclccserver
    thor1.eclscheduler=myeclscheduler

    roxie1.name=roxie1
    #Will use default values for the rest
    #
    roxie2.name=roxie2

  {{- if (eq "aws" .Values.Cloud.Type) }}
  roxie.properties: |
    default.roxieMulticastEnabled=false
  {{- end }}
