apiVersion: apps/v1
kind: Deployment
metadata:
  name: support
  labels:
    app: support
spec:  # specification of the pod’s contents
  replicas: 1
  selector:
    matchLabels:
      app: support
      cluster: support
  template:
    metadata:
      labels:
        app: support
        cluster: support
    spec:
      containers:
        - name: support
          image: "hpccsystems/platform"
          volumeMounts:
            - mountPath: /var/lib/HPCCSystems/hpcc-data
              name: hpcc-data
            - mountPath: /var/lib/HPCCSystems/hpcc-data1
              name: hpcc-data1
            - mountPath: /var/lib/HPCCSystems/hpcc-data2
              name: hpcc-data2
            - mountPath: /var/lib/HPCCSystems/hpcc-data3
              name: hpcc-data3
            - mountPath: /var/lib/HPCCSystems/hpcc-mirror
              name: hpcc-mirror
              #- mountPath: /var/lib/HPCCSystems/mydropzone #doesn't change owner to hpcc by HPCC Platform
              #name: dropzone
      volumes:
        - name: hpcc-data
          hostPath:
            path: /HPCCSystems/hpcc-data
            type: DirectoryOrCreate
        - name: hpcc-data1
          hostPath:
            path: /HPCCSystems/hpcc-data1
            type: DirectoryOrCreate
        - name: hpcc-data2
          hostPath:
            path: /HPCCSystems/hpcc-data2
            type: DirectoryOrCreate
        - name: hpcc-data3
          hostPath:
            path: /HPCCSystems/hpcc-data3
            type: DirectoryOrCreate
        - name: hpcc-mirror
          hostPath:
            path: /HPCCSystems/hpcc-mirror
            type: DirectoryOrCreate
            #- name: dropzone
            #hostPath:
            #path: /HPCCSystems/dropzone
            #type: DirectoryOrCreate
