apiVersion: v1
kind: Pod
metadata:
  name: dali
spec:  # specification of the pod’s contents
  restartPolicy: Never
  containers:
  - name:  dali
    image: "hpccsystems/platform"
    volumeMounts:
    - mountPath: "/var/lib/HPCCSystems/hpcc-data"
      name: dali-data
    - mountPath: "/var/lib/HPCCSystems/hpcc-mirror"
      name: dali-mirror
    resources:
      requests:
        cpu: "4"
        memory: "8Gi"
  volumes:
  - name: dali-data
    persistentVolumeClaim:
      claimName: efs-data
  - name: dali-mirror
    persistentVolumeClaim:
      claimName: efs-mirror
