apiVersion: apps/v1
kind: Deployment
metadata:
  name: support
  labels:
    app: support
spec:  # specification of the pod’s contents
  replicas: 1
  selector:
    matchLabels:
      app: support
  template:
    metadata:
      labels:
        app: support
    spec:
      containers:
      - name: support
        image: "hpccsystems/platform"
        volumeMounts:
        - mountPath: "/var/lib/HPCCSystems"
          name: support-data
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
      volumes:
      - name: support-data
        persistentVolumeClaim:
          claimName: efs
