apiVersion: apps/v1
kind: Deployment
metadata:
  name: roxie-roxie2
spec:  # specification of the pod’s contents
  replicas: 1
  selector:
    matchLabels:
      app: roxie-roxie2
  template:
    metadata:
      labels:
        app: roxie-roxie2
    spec:
      containers:
      - name:  roxie-roxie2
        image: "hpccsystems/platform"
        ports:
        - name: roxie
          containerPort: 9876
        - name: roxie-secure
          containerPort: 19876
        volumeMounts:
        -  name: roxie2-efs-data
           mountPath: "/var/lib/HPCCSystems/hpcc-data"
        -  name: roxie2-efs-mirror
           mountPath: "/var/lib/HPCCSystems/hpcc-mirror"
        -  name: roxie2-efs-queries
           mountPath: "/var/lib/HPCCSystems/queries"
      volumes:
      - name: roxie2-efs-data
        persistentVolumeClaim:
          claimName: efs-data
      - name: roxie2-efs-mirror
        persistentVolumeClaim:
          claimName: efs-mirror
      - name: roxie2-efs-queries
        persistentVolumeClaim:
          claimName: efs-queries
