#!/bin/bash
################################################################################
#    HPCC SYSTEMS software Copyright (C) 2019 HPCC Systems®   .
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
################################################################################
WORK_DIR=$(dirname $0)
. ${WORK_DIR}/../../../bin/common

# Apply configmap "hpcc-config" if bootstrap with bin/bootstrap-rbac-only.sh
#${KUBECTLTL} create configmap hpcc-config  --from-file=${WORK_DIR}/hpcc-config/

${KUBECTL} create -f admin.yaml
${KUBECTL} create -f dali.yaml
${KUBECTL} create -f support.yaml
${KUBECTL} create -f esp-e1.yaml
${KUBECTL} create -f roxie-r1.yaml
${KUBECTL} create -f roxie-r2.yaml
${KUBECTL} create -f thormaster-t1.yaml
${KUBECTL} create -f thor-t1.yaml
