#!/bin/bash
WORK_DIR=$(dirname $0)
. ${WORK_DIR}/../../../bin/common

# Apply configmap "hpcc-config" if bootstrap with bin/bootstrap-rbac-only.sh
#${KUBECTLTL} create configmap hpcc-config  --from-file=${WORK_DIR}/hpcc-config/

${KUBECTL} create -f admin.yaml
${KUBECTL} create -f dali.yaml
${KUBECTL} create -f support.yaml
${KUBECTL} create -f esp-e1.yaml
${KUBECTL} create -f roxie-r1.yaml
${KUBECTL} create -f roxie-r2.yaml
${KUBECTL} create -f thormaster-t1.yaml
${KUBECTL} create -f thor-t1.yaml
